USE [master]
GO

/****** Object:  Database [constructora-diseño]    Script Date: 23/04/2020 04:24:34 p. m. ******/
CREATE DATABASE [constructora-diseño]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'constructora-diseño', FILENAME = N'C:\Users\sams\constructora-diseño.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'constructora-diseño_log', FILENAME = N'C:\Users\sams\constructora-diseño_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [constructora-diseño].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [constructora-diseño] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [constructora-diseño] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [constructora-diseño] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [constructora-diseño] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [constructora-diseño] SET ARITHABORT OFF 
GO

ALTER DATABASE [constructora-diseño] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [constructora-diseño] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [constructora-diseño] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [constructora-diseño] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [constructora-diseño] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [constructora-diseño] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [constructora-diseño] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [constructora-diseño] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [constructora-diseño] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [constructora-diseño] SET  DISABLE_BROKER 
GO

ALTER DATABASE [constructora-diseño] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [constructora-diseño] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [constructora-diseño] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [constructora-diseño] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [constructora-diseño] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [constructora-diseño] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [constructora-diseño] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [constructora-diseño] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [constructora-diseño] SET  MULTI_USER 
GO

ALTER DATABASE [constructora-diseño] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [constructora-diseño] SET DB_CHAINING OFF 
GO

ALTER DATABASE [constructora-diseño] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [constructora-diseño] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [constructora-diseño] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [constructora-diseño] SET QUERY_STORE = OFF
GO

USE [constructora-diseño]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [constructora-diseño] SET  READ_WRITE 
GO

