USE [constructora-diseño]
GO

/****** Object:  Table [dbo].[cd_roles]    Script Date: 23/04/2020 04:17:06 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[cd_roles](
	[ROLES_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLES_NOMBRES] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ROLES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[cd_roles] ADD  DEFAULT (NULL) FOR [ROLES_NOMBRES]
GO



USE [constructora-diseño]
GO

/****** Object:  Table [dbo].[cd_usuarios]    Script Date: 23/04/2020 04:17:33 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[cd_usuarios](
	[USUARIOS_ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIOS_NOMBRE] [varchar](100) NULL,
	[USUARIOS_USUARIO] [varchar](100) NULL,
	[USUARIOS_CONTRASEÑA] [varchar](100) NULL,
	[USUARIOS_ROL] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[USUARIOS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[cd_usuarios] ADD  DEFAULT (NULL) FOR [USUARIOS_NOMBRE]
GO

ALTER TABLE [dbo].[cd_usuarios] ADD  DEFAULT (NULL) FOR [USUARIOS_USUARIO]
GO

ALTER TABLE [dbo].[cd_usuarios] ADD  DEFAULT (NULL) FOR [USUARIOS_CONTRASEÑA]
GO

ALTER TABLE [dbo].[cd_usuarios]  WITH CHECK ADD  CONSTRAINT [FK_cd_usuarios_cd_roles] FOREIGN KEY([USUARIOS_ROL])
REFERENCES [dbo].[cd_roles] ([ROLES_ID])
GO

ALTER TABLE [dbo].[cd_usuarios] CHECK CONSTRAINT [FK_cd_usuarios_cd_roles]
GO


